# Generated by Django 3.2.9 on 2021-11-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211113_2051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='users_customuser_unique',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
