# Generated by Django 3.2.9 on 2021-11-13 19:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[users.models.CustomUser.validate_not_empty]),
        ),
    ]
