# Generated by Django 3.2.9 on 2021-11-13 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_tables_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(13), django.core.validators.MinValueValidator(1)]),
        ),
    ]
